#!/bin/bash
#
#Enviorment declaration
export GUM_CONFIRM_SELECTED_FOREGROUND="#fbf1c7"
export GUM_CONFIRM_SELECTED_PADDING=""
export GUM_CONFIRM_SELECTED_BACKGROUND="#79740e"
export GUM_CONFIRM_SELECTED_MARGIN="2 9"
export GUM_CONFIRM_UNSELECTED_MARGIN="2 9"
export GUM_CONFIRM_UNSELECTED_PADDING=""
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#fbf1c7"
export GUM_CONFIRM_PROMPT_MARGIN=""
export GUM_CONFIRM_PROMPT_FOREGROUND="#fbf1c7"
export GUM_CHOOSE_CURSOR_FOREGROUND="#79740e"
export GUM_CHOOSE_ITEM_FOREGROUND="#fbf1c7"
export GUM_CHOOSE_ITEM_MARGIN="0 5"
export GUM_CHOOSE_CURSOR_MARGIN="0 2"
export GUM_INPUT_PROMPT_FOREGROUND="#fbf1c7"
export GUM_INPUT_PROMPT_MARGIN="0 3"
export GUM_INPUT_CURSOR_MARGIN="0 -2"
export GUM_INPUT_CURSOR_FOREGROUND="#79740e"
export GUM_SPIN_SPINNER_MARGIN="0 10"
export GUM_SPIN_SPINNER_FOREGROUND="#fbf1c7"
export GUM_SPIN_TITLE_FOREGROUND="#fbf1c7"


#Main loop
while true; do
clear
gum style \
	--foreground "#fbf1c7" --border-foreground "#79740e" --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'sshm' 'your ssh connection manager!'

menuselectinput=$(cat ~/scripts/sshm/menu | gum choose --limit=1) 
menuselect="$(echo $menuselectinput | grep -Eo "[0-9]+")"

case $menuselect in
        1)
            #Connect
            #Get information from JSON

	    sshselect=$(cat /home/user1/scripts/sshm/connections.json | jq '.connections[].name' | gum choose)
          
	    sshid=$(cat ~/scripts/sshm/connections.json | jq '.connections[] | select (.name=='$sshselect')' | jq '.ID')
            sshhost=$(cat ~/scripts/sshm/connections.json | jq '.connections[] | select (.ID=='$sshid')' | jq '.hostname')
            sshun=$(cat ~/scripts/sshm/connections.json | jq '.connections[] | select (.ID=='$sshid')' | jq '.username')
           
#            if [[ "$sshselect" == '"back"' ]] 
#	    then
#		    echo ""
#			else
            #open SSH Connection
            
	    gum confirm "Do you wanna connect?" && gum spin --spinner dot --title "loading connection" -- sleep 3 && eval ssh $sshun@$sshhost || echo "abort"
#            fi
            ;;
        
        2)
            #Add connection
            #Get User Input
            newsshname=$(gum input --prompt "What's the name of this new Connection: " --placeholder "DHCP")
            newsshhostname=$(gum input --prompt "What Hostname shoud we use?: " --placeholder "sun.enterprise.com")
            newsshun=$(gum input --prompt "What user should we use to connect?: " --placeholder "root")

            #Find highest ID
            highestid=$(cat ~/scripts/sshm/connections.json | jq -r 'map(.[].ID) | max')
            nextid=$((highestid+1))
            
           #Write JSON entry
            touch ~/scripts/sshm/tmp.json
            jq '.connections += [{"ID": "'$nextid'", "name": "'$newsshname'", "hostname": "'$newsshhostname'", "username": "'$newsshun'"}]' ~/scripts/sshm/connections.json | cat >> ~/scripts/sshm/tmp.json
            mv ~/scripts/sshm/tmp.json ~/scripts/sshm/connections.json
	        
            touch ~/scripts/sshm/tmpss.json
            jq '.connections += [{"ID": "'$nextid'", "name": "'$newsshname'", "hostname": "'$newsshhostname'", "username": "'$newsshun'"}]' ~/scripts/sshm/connectionsss.json | cat >> ~/scripts/sshm/tmpss.json
            mv ~/scripts/sshm/tmpss.json ~/scripts/sshm/connectionsss.json

            ;; 
        3)
            #Exit
            gum confirm "close sshm?" && echo "Closing Script" && exit 0 || echo "Okay"
	    ;;
    esac
done
