#!/bin/bash
#
#Enviorment declaration
export GUM_CHOOSE_ITEM_COLOR="#fbf1c7"
export GUM_CHOOSE_HEADER_FOREGROUND="#79740e"
export GUM_CHOOSE_CURSOR_FOREGROUND="#79740e"
export GUM_CHOOSE_SELECTED_FOREGROUND="#d79921"
export GUM_CONFIRM_SELECTED_FOREGROUND="#fbf1c7"
export GUM_CONFIRM_SELECTED_BACKGROUND="#79740e"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="#fbf1c7"
export GUM_CONFIRM_PROMPT_FOREGROUND="#fbf1c7"
export GUM_SPIN_SPINNER_FOREGROUND="#fbf1c7"
export GUM_SPIN_TITLE_FOREGROUND="#fbf1c7"
export GUM_SPIN_SPINNER_MARGIN="0 10"
export GUM_WRITE_PROMPT_FOREGROUND="#fbf1c7"
export GUM_WRITE_CURSOR_FOREGROUND="#79740e"
export GUM_SPIN_SPINNER_MARGIN="0 10"
#Main loop
#put path here:
loc="/home/user1/sshm"
while true; do
clear
gum style \
	--foreground "#fbf1c7" --border-foreground "#79740e" --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'sshm' 'your ssh connection manager!'

menuselectinput=$(cat "$loc"/menu | gum choose --limit=1) 
menuselect="$(echo $menuselectinput | grep -Eo "[0-9]+")"

case $menuselect in
        1)
            #Connect
            #Get information from JSON

	        sshselect=$(cat "$loc"/connections.json | jq '.connections[].name' | gum choose)
            sshid=$(cat "$loc"/connections.json  | jq '.connections[] | select (.name=='$sshselect')' | jq '.ID')
            sshhost=$(cat "$loc"/connections.json | jq '.connections[] | select (.ID=='$sshid')' | jq '.hostname')
            sshun=$(cat "$loc"/connections.json | jq '.connections[] | select (.ID=='$sshid')' | jq '.username')
           
            if [[ $sshselect == '"back"' ]];
	    then
		    echo ""
			else
            #open SSH Connection
            
	    gum confirm "Do you wanna connect?" && gum spin --spinner dot --title "loading connection" -- sleep 3 && eval ssh $sshun@$sshhost || echo "abort"
            fi
            ;;
        
        2)
            #Add connection
            #Get User Input
            newsshname=$(gum write --prompt "What's the name of this new Connection: " --placeholder "DHCP")
            newsshhostname=$(gum write --prompt "What Hostname shoud we use?: " --placeholder "sun.enterprise.com")
            newsshun=$(gum write --prompt "What user should we use to connect?: " --placeholder "root")

            #Find highest ID
            highestid=$(cat "$loc"/connections.json | jq -r 'map(.[].ID) | max')
            nextid=$((highestid+1))

            gum style \
	            --foreground "#fbf1c7" --border-foreground "#79740e" --border double \
            	--align center --width 50 --margin "1 2" --padding "2 4" \
	            "*NEW CONNECTION*" " " "Name: $newsshname" "Hostname: $newsshhostname" "User: $newsshun"


            
            gum confirm "Are the values above correct?" && entryconfirm="1" || entryconfirm="0"

            if [[ "$entryconfirm" == "1" ]];
            then

            #Write JSON entry
            touch "$loc"/tmp.json
            jq '.connections += [{"ID": "'$nextid'", "name": "'$newsshname'", "hostname": "'$newsshhostname'", "username": "'$newsshun'"}]' "$loc"/connections.json | cat >> "$loc"/tmp.json
            cp "$loc"/tmp.json "$loc"/connections.json
            rm "$loc"/tmp.json

        else
            echo "abort"
            fi
            ;;  
        3)
            #Exit
            gum confirm "close sshm?" && echo "Closing Script" && exit 0 || echo "Okay"
            ;;
    esac
done
